### ISSUE TITLE
The URL https://s3-eu-west-1.amazonaws.com/nice-dcv-publish/NICE-GPG-KEY does not exist

### ISSUE THREAD

**Issue by rubenanapu** [aws-samples/aws-batch-using-nice-dcv#4]
Hi

if we try to create an image, it fails at this point: [aws-batch-using-nice-dcv.dockerfile#L47](https://github.com/aws-samples/aws-batch-using-nice-dcv/blob/master/aws-batch-using-nice-dcv.dockerfile#L47)

It says:
> curl: (22) The requested URL returned error: 403
> error: https://s3-eu-west-1.amazonaws.com/nice-dcv-publish/NICE-GPG-KEY: import read failed(2).

Indeed, the URL https://s3-eu-west-1.amazonaws.com/nice-dcv-publish/NICE-GPG-KEY reports:
``` <Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>EYMSGQY3RFZ084KN</RequestId>
<HostId>SY8xrEsxXzWlhB52o+zHhp5/hbhVlUrl0s7ZtFIr4onH4S6SnbzV4zk/kNBdKwynmISfAy0RRUI=</HostId>
</Error>
```

**Comment by afalzonelab** [comment]
Hi,
thank you for pointing out this issue,
new link is on official documentation https://docs.aws.amazon.com/dcv/latest/adminguide/setting-up-installing-linux-server.html

Already fixed on docker file.
Regards
